Movie_App/Models/Categories.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Movie_App.Models
{
    public class Categories
    {
        [Key]
        public int catagory_id { get; set; }
        public string name { get; set; }
    }
}

Movie_App/Models/Movie.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Movie_App.Models
{
    public class Movie
    {
        [Key]
        public int movie_id { get; set; }
        public string name { get; set; }
        public string image { get; set; }
        public string description { get; set; }
        public int? cat_id { get; set; }
        [ForeignKey("cat_id")]
        public virtual Categories Categories { get; set; }
    }
}

Movie_App/Models/db_movieEntities.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace Movie_App.Models
{
    public class db_movieEntities : DbContext
    {
        public DbSet<Movie> tb_movies { get; set; }
        public DbSet<Categories> tb_Categories { get; set; }
    }
}

Movie_App/Controllers/CategoryController.cs
using Movie_App.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Movie_App.Controllers
{
    public class CategoryController : Controller
    {
        db_movieEntities db = new db_movieEntities();
        // GET: Category
        public ActionResult Index()
        {
            var category = db.tb_Categories.ToList();
            return View(category);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Categories categories)
        {
            //var isCategoryExist = db.tb_movies.Any(x => x.name.Equals(categories.name));

            //if (isCategoryExist)
            //{
            //    ModelState.AddModelError("Category name", "Category already exits");
            //    return View(categories);
            //}

            Categories c = new Categories();
            c.name = categories.name;
            db.tb_Categories.Add(c);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int?id)
        {
            Categories c = new Categories();
            c = db.tb_Categories.Where(x => x.catagory_id == id).SingleOrDefault();
            return View(c);
        }
        [HttpPost]
        public ActionResult Edit(int? id, Categories categories)
        {
            Categories c = new Categories();
            c = db.tb_Categories.Where(x => x.catagory_id == id).SingleOrDefault();
            c.name = categories.name;
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        [HttpGet]
        public ActionResult Delete(int? id)
        {
            Categories c = new Categories();
            c = db.tb_Categories.Where(x => x.catagory_id == id).SingleOrDefault();
            return View(c);
        }
        [HttpPost]
        public ActionResult Delete(int? id, Categories categories)
        {
            Categories c = new Categories();
            c = db.tb_Categories.Where(x => x.catagory_id == id).SingleOrDefault();
            c.name = categories.name;
            db.tb_Categories.Remove(c);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Details(int? id)
        {
            Categories c = new Categories();
            c = db.tb_Categories.Where(x => x.catagory_id == id).SingleOrDefault();
            return View(c);
        }
    }
}

Movie_App/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Movie_App.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Movie_App/Controllers/MovieController.cs
using Movie_App.Models;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Movie_App.Controllers
{
    public class MovieController : Controller
    {
        db_movieEntities db = new db_movieEntities();
        // GET: Movie
        public ActionResult Index()
        {

            return View(db.tb_movies.ToList());

        }

        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.CategoriesList = new SelectList(db.tb_Categories, "catagory_id", "name");
            return View();
        }
        [HttpPost]
        public ActionResult Create(HttpPostedFileBase imageFile, Movie movie)
        {
            ViewBag.CategoriesList = new SelectList(db.tb_Categories, "catagory_id", "name");
            //var isMovieExist = db.tb_movies.Any(x => x.name.Equals(movie.name));

            //if (isMovieExist)
            //{
            //    ModelState.AddModelError("Movie name", "Movie already exits");
            //    return View(movie);
            //}


            Movie m = new Movie();
            m.name = movie.name;
            m.image = movie.image;
            m.description = movie.description;
            m.cat_id = movie.cat_id;
            string fileName = Path.GetFileNameWithoutExtension(imageFile.FileName);
            string extension = Path.GetExtension(imageFile.FileName);
            fileName = fileName + extension;
            m.image = "~/Images/" + fileName;
            fileName = Path.Combine(Server.MapPath("~/Images/"), fileName);
            imageFile.SaveAs(fileName);
            db.tb_movies.Add(m);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            Movie m = new Movie();
            m = db.tb_movies.Where(x => x.movie_id == id).SingleOrDefault();
            ViewBag.CategoriesList = new SelectList(db.tb_Categories, "catagory_id", "name");
            Session["Image"] = m.image;
            return View(m);
        }
        [HttpPost]
        public ActionResult Edit(int? id, HttpPostedFileBase imageFile, Movie movie)
        {
            ViewBag.CategoriesList = new SelectList(db.tb_Categories, "catagory_id", "name");

            Movie m = new Movie();
            m = db.tb_movies.Where(x => x.movie_id == id).SingleOrDefault();
            m.name = movie.name;
            m.image = movie.image;
            m.description = movie.description;
            m.cat_id = movie.cat_id;
            if (m.image != null)
            {
                string fileName = Path.GetFileNameWithoutExtension(imageFile.FileName);
                string extension = Path.GetExtension(imageFile.FileName);
                fileName = fileName + extension;
                m.image = "~/Images/" + fileName;
                fileName = Path.Combine(Server.MapPath("~/Images/"), fileName);
                imageFile.SaveAs(fileName);
                db.Entry(m).State = EntityState.Modified;
                db.SaveChanges();
            }
            else
            {
                m.image = Session["Image"].ToString();
                db.Entry(m).State = EntityState.Modified;
                db.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Delete(int? id)
        {
            Movie m = new Movie();
            m = db.tb_movies.Where(x => x.movie_id == id).SingleOrDefault();
            return View(m);
        }
        [HttpPost]
        public ActionResult Delete(int? id, Movie movie)
        {

            Movie m = new Movie();
            m = db.tb_movies.Where(x => x.movie_id == id).SingleOrDefault();
            m.name = movie.name;
            m.image = movie.image;
            m.description = movie.description;
            m.cat_id = movie.cat_id;
            db.tb_movies.Remove(m);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Details(int? id)
        {
            Movie m = new Movie();
            m = db.tb_movies.Where(x => x.movie_id == id).SingleOrDefault();
            return View(m);
        }
    }
}

Movie_App/Views/Category/Create.cshtml
@model Movie_App.Models.Categories

@{
    ViewBag.Title = "Create";
}

<h2>Add Category</h2>

@using (Html.BeginForm("Create", "Category", FormMethod.Post))
{
    <label>Category Name</label>
    @Html.TextBoxFor(x => x.name, new { @class = "form-control" })

    <br />
    <input type="submit" value="Add Category" />

}

@Html.ActionLink("Back to List", "Index")

Movie_App/Views/Category/Delete.cshtml
@model Movie_App.Models.Categories

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>
<h3>Are you sure you want to delete this?</h3>

<table class="table">
    <tr>
        <th>Category Name</th>
        <td>@Model.name</td>
    </tr>
</table>
<br />

@using (Html.BeginForm("Delete", "Category", FormMethod.Post))
{
    <input type="submit" value="Delete" />
    @Html.ActionLink("Back to List", "Index")
}

Movie_App/Views/Category/Details.cshtml
@model Movie_App.Models.Categories

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<table class="table">
    <tr>
        <th>Category Name</th>
        <td>@Model.name</td>
    </tr>
</table>

@Html.ActionLink("Back to List", "Index")

Movie_App/Views/Category/Edit.cshtml
@model Movie_App.Models.Categories

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Category", FormMethod.Post))
{
    <label>Category Name</label>
    @Html.TextBoxFor(x => x.name, new { @class = "form-control" })

    <br />
    <input type="submit" value="Edit Category" />

}

@Html.ActionLink("Back to List", "Index")

Movie_App/Views/Category/Index.cshtml
@model IEnumerable<Movie_App.Models.Categories>

@{
    ViewBag.Title = "Index";
}

<h2>Movie Categories</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Actions</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.catagory_id</td>
                <td>@item.name</td>
                
                <td>
                    <a href="@Url.Action("Details", new { id = item.catagory_id })">Details</a> |
                    <a href="@Url.Action("Edit", new { id = item.catagory_id })">Edit</a> |
                    <a href="@Url.Action("Delete", new { id = item.catagory_id })">Delete</a>
                </td>
            </tr>
        }
    </tbody>

</table>

Movie_App/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Movie_App/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Movie_App/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Movie_App/Views/Movie/Create.cshtml
@model Movie_App.Models.Movie

@{
    ViewBag.Title = "Create";
}

<h2>Add Movie</h2>

@using (Html.BeginForm("Create", "Movie", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <label>Movie Name</label>
    @Html.TextBoxFor(x => x.name, new { @class = "form-control", placeholder = "Movie Name" })

    <label>Image</label>
    <input type="file" id="imageFile" name="imageFile" onchange="ChangeShownImage(event)"/>
    <script>
        function ChangeShownImage(event) {
            document.getElementById("shownImage").src = URL.createObjectURL(event.target.files[0]);
    }</script>
    <img src="@Html.DisplayFor(x => x.image)" width="60" height="60" id="shownImage"/>
    <br />

    <label>Description</label>
    @Html.TextAreaFor(x => x.description, new { @class = "form-control", @placeholder = "Movie Description" })

    <label>Category</label>
    @Html.DropDownListFor(x => x.cat_id, ViewBag.CategoriesList as SelectList, "Select Category", new { @class = "form-control" })

    <br />
    <input type="submit" value="Add" />

}

@Html.ActionLink("Back to List", "Index")

Movie_App/Views/Movie/Delete.cshtml
@model Movie_App.Models.Movie

@{
    ViewBag.Title = "Delete";
}

<h2>Delete Movie</h2>
<h3>Are you sure you want to delete this?</h3>

<table class="table">
    <tr>
        <th>Movie Name</th>
        <td>@Model.name</td>
    </tr>
    <tr>
        <th>Image</th>
        <td>@Model.image</td>
    </tr>
    <tr>
        <th>Description</th>
        <td>@Model.description</td>
    </tr>
    <tr>
        <th>Category</th>
        <td>@Model.Categories.name</td>
    </tr>
</table>
<br />

@using (Html.BeginForm("Delete", "Movie", FormMethod.Post))
{
    <input type="submit" value="Delete" />
    @Html.ActionLink("Back to List", "Index")
}

Movie_App/Views/Movie/Details.cshtml
@model Movie_App.Models.Movie

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<table class="table">
    <tr>
        <th>Movie Name</th>
        <td>@Model.name</td>
    </tr>
    <tr>
        <th>Image</th>
        <td>@Model.image</td>
    </tr>
    <tr>
        <th>Description</th>
        <td>@Model.description</td>
    </tr>
    <tr>
        <th>Category</th>
        <td>@Model.Categories.name</td>
    </tr>
</table>

@Html.ActionLink("Back to List", "Index")

Movie_App/Views/Movie/Edit.cshtml
@model Movie_App.Models.Movie

@{
    ViewBag.Title = "Edit";
}

<h2>Edit Movie</h2>

@using (Html.BeginForm("Edit", "Movie", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <label>Movie Name</label>
    @Html.TextBoxFor(x => x.name, new { @class = "form-control", placeholder = "Movie Name" })

    <label>Image</label>
    <input type="file" id="imageFile" name="imageFile" onchange="ChangeShownImage(event)"/>
    <script>
        function ChangeShownImage(event) {
            document.getElementById("shownImage").src = URL.createObjectURL(event.target.files[0]);
    }</script>
    <img src="@Url.Content(Session["Image"].ToString())" width="60" height="60" id="shownImage"/>
    <br />

    <label>Description</label>
    @Html.TextAreaFor(x => x.description, new { @class = "form-control", @placeholder = "Movie Description" })

    <label>Category</label>
    @Html.DropDownListFor(x => x.cat_id, ViewBag.CategoriesList as SelectList, "Select Category", new { @class = "form-control" })

    <br />
    <input type="submit" value="Save" />

}

@Html.ActionLink("Back to List", "Index")

Movie_App/Views/Movie/Index.cshtml
@model IEnumerable<Movie_App.Models.Movie>

@{
    ViewBag.Title = "Index";
}

<h2>Movies List</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <thead>
        <tr>
            <th>Movie Name</th>
            <th>Image</th>
            <th>Description</th>
            <th>Category</th>
            <th>Actions</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(x => item.name)</td>
                <td><img src="@Url.Content(item.image)" width="60" height="60"/></td>
                <td>@Html.DisplayFor(x => item.description)</td>
                <td>@Html.DisplayFor(x => item.Categories.name)</td>
                <td>
                    <a href="@Url.Action("Details", new { id = item.movie_id })">Details</a> |
                    <a href="@Url.Action("Edit", new { id = item.movie_id })">Edit</a> |
                    <a href="@Url.Action("Delete", new { id = item.movie_id })">Delete</a>
                </td>
            </tr>
        }
    </tbody>

</table>

Movie_App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>